name: main
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --recursive --extensions=hpp,cpp,cu .
  tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Zackere/cpp-linter-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: mkdir bin
    - run: cd bin
    - run: cmake -DPIPELINE_ENV=True .
    - run: make
