name: main
on: [pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --recursive --extensions=hpp,cpp,cu .
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - name : clang-tidy
        uses: smay1613/clang-tidy-action@master
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
